### ISSUE TITLE
Create bash script that "create the database table (for the first time)"

### ISSUE THREAD

**Issue by mr54ndm4n** [DreamN/Pic-storage#1]
for now
```bash
    $python
    >>> import app
    >>> app.createDBTable()
```

**Comment by amirmazmi** [comment]
Hi, can i try this?

**Comment by mr54ndm4n** [comment]
@amirmazmi Sure! Include *pip install* would be great also (named "setup.sh")

**Comment by amirmazmi** [comment]
@DreamN  Done. I couldn't find the option to squash commits.

**Comment by mr54ndm4n** [comment]
@amirmazmi Merged!, Thanks : )

**Comment by amirmazmi** [comment]
@DreamN That was my first PR. Thanks to you!

**Comment by mr54ndm4n** [comment]
@amirmazmi  Awesome! :)
